import type { NeedsReport } from "../supabase";

export type NeedsSummary = {
  titleEnglish: string;
  titleFilipino: string;
  bodyEnglish: string;
  bodyFilipino: string;
  generatedAt: string;
};

export type AggregatedNeeds = {
  totalReports: number;
  totalEvacuees: number;
  totalFoodPacks: number;
  totalWaterLiters: number;
  totalBlankets: number;
  needsMedicine: boolean;
  medicalCasesCount: number;
  medicalCasesList: string[];
  pendingReportsCount: number;
};

export function aggregateNeedsReports(reports: NeedsReport[]): AggregatedNeeds {
  const pendingReports = reports.filter((r) => r.status === "pending");

  return {
    totalReports: reports.length,
    totalEvacuees: pendingReports.reduce((sum, r) => sum + r.total_evacuees, 0),
    totalFoodPacks: pendingReports.reduce((sum, r) => sum + r.needs_food_packs, 0),
    totalWaterLiters: pendingReports.reduce((sum, r) => sum + r.needs_water_liters, 0),
    totalBlankets: pendingReports.reduce((sum, r) => sum + r.needs_blankets, 0),
    needsMedicine: pendingReports.some((r) => r.needs_medicine),
    medicalCasesCount: pendingReports.filter((r) => r.medical_cases).length,
    medicalCasesList: pendingReports
      .map((r) => r.medical_cases)
      .filter((mc): mc is string => Boolean(mc)),
    pendingReportsCount: pendingReports.length,
  };
}

export function buildNeedsSummary(
  aggregated: AggregatedNeeds,
  barangayName: string,
): NeedsSummary {
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-PH", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });

  const titleEnglish = `NEEDS SITUATION REPORT - ${barangayName}`;
  const titleFilipino = `ULAT NG SITWASYON NG PANGANGAILANGAN - ${barangayName}`;

  const medicalCasesText = aggregated.medicalCasesList.length > 0
    ? aggregated.medicalCasesList.map((mc, i) => `  ${i + 1}. ${mc}`).join("\n")
    : "  None reported";

  const medicalCasesTextFilipino = aggregated.medicalCasesList.length > 0
    ? aggregated.medicalCasesList.map((mc, i) => `  ${i + 1}. ${mc}`).join("\n")
    : "  Walang naiulat";

  const bodyEnglish = `Date: ${dateStr}

EVACUATION STATUS:
- Total Evacuees: ${aggregated.totalEvacuees.toLocaleString()}
- Active Reports: ${aggregated.pendingReportsCount}

SUPPLY NEEDS:
- Food Packs: ${aggregated.totalFoodPacks.toLocaleString()}
- Water: ${aggregated.totalWaterLiters.toLocaleString()} liters
- Blankets: ${aggregated.totalBlankets.toLocaleString()}
- Medicine Required: ${aggregated.needsMedicine ? "Yes" : "No"}

MEDICAL CASES (${aggregated.medicalCasesCount}):
${medicalCasesText}

---
Generated by AGAP DRRM System
This report summarizes ${aggregated.pendingReportsCount} pending needs report(s).`;

  const bodyFilipino = `Petsa: ${dateStr}

KALAGAYAN NG EBAKWASYON:
- Kabuuang Evacuees: ${aggregated.totalEvacuees.toLocaleString()}
- Aktibong Ulat: ${aggregated.pendingReportsCount}

PANGANGAILANGAN NG SUPLAY:
- Food Packs: ${aggregated.totalFoodPacks.toLocaleString()}
- Tubig: ${aggregated.totalWaterLiters.toLocaleString()} litro
- Kumot: ${aggregated.totalBlankets.toLocaleString()}
- Kailangan ng Gamot: ${aggregated.needsMedicine ? "Oo" : "Hindi"}

MGA KASO NG MEDIKAL (${aggregated.medicalCasesCount}):
${medicalCasesTextFilipino}

---
Binuo ng AGAP DRRM System
Ang ulat na ito ay buod ng ${aggregated.pendingReportsCount} pending needs report(s).`;

  return {
    titleEnglish,
    titleFilipino,
    bodyEnglish,
    bodyFilipino,
    generatedAt: now.toISOString(),
  };
}

export function getNeedsSummaryText(
  summary: NeedsSummary,
  language: "english" | "filipino",
): string {
  if (language === "filipino") {
    return [summary.titleFilipino, "", summary.bodyFilipino].join("\n");
  }
  return [summary.titleEnglish, "", summary.bodyEnglish].join("\n");
}
